---
- name: Installing virtualenv
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ virtualenv_packages }}"
  become: true
  # The venv utility was officially added in Python 3.3.
  when: (ansible_python['version']['major'] == 2) or
        ((ansible_python['version']['major'] == 3) and (ansible_python['version']['minor'] < 3))
  tags:
    - become

- name: Create the virtualenv
  command: "virtualenv {{ virtualenv_path_full }}"
  args:
    creates: "{{ virtualenv_path_full }}"
